[package]
name = "aligned-buffer-pool"
version = "0.0.0"
edition = "2021"
description = "A buffer-pool with controllable alignment."
license = "MIT"
authors = ["Aleksander Heintz <alxandr@alxandr.me>"]
repository = "https://github.com/YoloDev/rkyv-utils"
keywords = ["buffer", "rkyv", "bytes"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aligned-buffer = { version = "0.0.3", path = "../aligned-buffer", features = ["rkyv"] }
crossbeam-queue = "0.3.11"
fxhash = { version = "0.2.1", default-features = false }
rkyv = { version = "0.8.0-pre1", default-features = false, features = ["std", "bytecheck"], git = "https://github.com/rkyv/rkyv", rev = "be38ebe926bf8bb4898af472ba7ce90f72df74bd" }
