[package]
name = "aligned-buffer-pool"
version = "0.0.1"
edition = "2021"
description = "A buffer-pool with controllable alignment."
license = "MIT"
authors = ["Aleksander Heintz <alxandr@alxandr.me>"]
repository = "https://github.com/YoloDev/rkyv-utils"
keywords = ["buffer", "rkyv", "bytes"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aligned-buffer = { version = "0.0.5", path = "../aligned-buffer", default-features = false, features = ["rkyv"] }
crossbeam-queue = "0.3.11"
fxhash = { version = "0.2.1", default-features = false }
rkyv = { version = "0.8.0-alpha.1", default-features = false, features = ["std", "bytecheck"] }
