[package]
name = "aligned-buffer"
version = "0.0.0"
edition = "2021"
description = "A buffer with controllable alignment, that can be sealed and shared by reference count."
license = "MIT"
authors = ["Aleksander Heintz <alxandr@alxandr.me>"]
repository = "https://github.com/YoloDev/rkyv-utils"
keywords = ["buffer", "rkyv", "bytes"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const_panic = { version = "0.2.8", default-features = false }
thiserror = "1.0.56"
