[package]
name = "aligned-buffer"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const_panic = { version = "0.2.8", default-features = false }
thiserror = "1.0.56"
